dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
addons:
  apt:
    packages:
      - ant
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/download
before_script: composer install
script:
  - echo "install OpenJDK 1.8.0_202 EA"
  - wget 'https://download.java.net/java/early_access/jdk8/b03/BCL/jre-8u202-ea-bin-b03-linux-x64-07_nov_2018.tar.gz'
  - tar xfz jre-8u202-ea-bin-b03-linux-x64-07_nov_2018.tar.gz
  - ./jre1.8.0_202/bin/java -version
  - java -version
  - CURR_DIR=`pwd`
  - export SOLR_JAVA_HOME="$CURR_DIR/jre1.8.0_202/"
  - echo "SOLR_JAVA_HOME is set to $JAVA_HOME"
  - mysql --version
  - mkdir -p tests/workspace/cache tests/workspace/files tests/workspace/log tests/workspace/tmp
  - php db/createdb.php
  - mysql opusdb -u root --password='' -e 'SELECT * FROM schema_version'
  - ant download-solr -DsolrVersion=5.5.5
  - cd solr-5.5.5
  - ./bin/solr start
  - ./bin/solr create -c opus4
  - cd server/solr/opus4/conf
  - rm -f managed-schema schema.xml solrconfig.xml
  - ln -s $HOME/vendor/opus4-repo/search/schema-5.xml schema.xml
  - ln -s $HOME/vendor/opus4-repo/search/solrconfig-5.xml solrconfig.xml
  - cd ../../../../
  - ./bin/solr restart
  - cd ..
  - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml
