dist: xenial
language: php
php:
  - 7.0
jdk:
  - oraclejdk8  
services:
  - mysql
before_script: composer install
script: 
  - mysql --version
  - java -version
  - mkdir -p tests/workspace/cache tests/workspace/files tests/workspace/log tests/workspace/tmp
  - php db/createdb.php
  - mysql opusdb -u root --password='' -e 'SELECT * FROM schema_version'
  - wget http://archive.apache.org/dist/lucene/solr/5.5.5/solr-5.5.5.tgz
  - tar xfz solr-5.5.5.tgz
  - cd solr-5.5.5
  - ./bin/solr start
  - ./bin/solr create -c solr
  - ls server/*
  - cd server/solr/solr
  - git clone https://github.com/OPUS4/opus4-search
  - cd conf
  - rm -f managed-schema schema.xml solrconfig.xml
  - ln -s ../opus4-search/schema.xml
  - ln -s ../opus4-search/solrconfig.xml
  - cd ../../../
  - ./bin/solr restart  
  - cd ..
  - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml
