dist: xenial
language: php
php:
  - 7.0
services:
  - mysql
before_script: composer install
script: 
  - mysql --version
  - java -version
  - mkdir -p tests/workspace/cache tests/workspace/files tests/workspace/log tests/workspace/tmp
  - php db/createdb.php
  - mysql opusdb -u root --password='' -e 'SELECT * FROM schema_version'
  - wget https://archive.apache.org/dist/lucene/solr/7.6.0/solr-7.6.0.tgz
  - tar xfz solr-7.6.6.tgz
  - cd solr-7.6.0
  - ./bin/solr start
  - ./bin/solr create -c opus4
  - cd server/solr/opus4
  - git clone https://github.com/OPUS4/opus4-search
  - cd opus4-search
  - git checkout 4.7
  - cd ../conf
  - rm -f managed-schema schema.xml solrconfig.xml
  - ln -s ../opus4-search/config/schema-5.xml schema.xml
  - ln -s ../opus4-search/config/solrconfig-5.xml solrconfig.xml
  - cd ../../../../
  - ./bin/solr restart  
  - cd ..
  - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml
